### ISSUE TITLE
Increase accuracy of Lat/Long -> UTM conversion function

### ISSUE THREAD

**Issue by Mauzey** [axessta/summer-project-2018#1]
**Location:** _summer-project-2018/stuff/utm_convertor/main.cpp_

**Issue:** The function utmToLl(); returns a latitude/longitude coordinate with an accuracy of 2 decimal places. This isn't enough for what we need.

**Comment by axessta** [comment]
Will look tomorrow. Nice find with libgeographic

**Comment by Mauzey** [comment]
Fixed issue, it was purely a cosmetic issue and wouldn't have had an effect on actual logic. Added `fixed << setprecision(5)` to line 41. If further adjustments are needed, the value in parenthesis determines the amount of decimal places to be printed.
